<a href="https://colab.research.google.com/github/Nihcas001/data_analysis_using_Python/blob/main/06(A)_Banking_dataset_operation_using_Numpy/Banking_transactions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Step 1 — Import NumPy
import numpy as np

Column 0 → Customer ID

Column 1 → Balance

Column 2 → Deposit

Column 3 → Withdrawal

Column 4 → EMI

Column 5 → Transactions

In [2]:
# Step 2 — Create the Dataset
data = np.array([
    [1001, 50000, 12000, 5000, 3000, 8],
    [1002, 72000, 15000, 7000, 4500, 12],
    [1003, 35000, 8000, 3000, 2500, 6],
    [1004, 91000, 20000, 9000, 6000, 15],
    [1005, 45000, 10000, 4000, 3000, 9],
    [1006, 68000, 14000, 6500, 4000, 11],
    [1007, 29000, 7000, 2500, 2000, 5],
    [1008, 83000, 18000, 8500, 5000, 14],
    [1009, 57000, 11000, 5500, 3500, 10],
    [1010, 102000, 25000, 12000, 7000, 18],
    [1011, 39000, 9000, 3500, 2500, 7],
    [1012, 76000, 16000, 7500, 4500, 13],
    [1013, 48000, 10500, 4500, 3000, 8],
    [1014, 95000, 22000, 10000, 6500, 16],
    [1015, 62000, 13000, 6000, 4000, 11]
])

print(data)

[[  1001  50000  12000   5000   3000      8]
 [  1002  72000  15000   7000   4500     12]
 [  1003  35000   8000   3000   2500      6]
 [  1004  91000  20000   9000   6000     15]
 [  1005  45000  10000   4000   3000      9]
 [  1006  68000  14000   6500   4000     11]
 [  1007  29000   7000   2500   2000      5]
 [  1008  83000  18000   8500   5000     14]
 [  1009  57000  11000   5500   3500     10]
 [  1010 102000  25000  12000   7000     18]
 [  1011  39000   9000   3500   2500      7]
 [  1012  76000  16000   7500   4500     13]
 [  1013  48000  10500   4500   3000      8]
 [  1014  95000  22000  10000   6500     16]
 [  1015  62000  13000   6000   4000     11]]


In [3]:
# Step 3 — Understand the Array
# Question 1: What is the number of dimensions?
print(data.ndim)

2


Because our data has: Rows × Columns

So it is a 2-dimensional array.

In [4]:
# Question 2: What is the shape?
print(data.shape)

(15, 6)


In [5]:
# Question 3: How many elements are present?
print(data.size)

90


Because: 15 × 6 = 90

In [6]:
# Question 4: What is the data type?
print(data.dtype)

int64


**Step 4 — Basic Indexing**

In [7]:
# Question 5: Display the first customer's complete record.
print(data[0])

[ 1001 50000 12000  5000  3000     8]


So:

data[0] → first row

data[1] → second row

data[2] → third row

In [8]:
# Question 6: Display the first customer's balance.
# Balance is column 1.

print(data[0, 1]) # data[row, column]

50000


In [9]:
# Question 7: Display customer ID of the 10th customer.
print(data[9, 0])

1010


**8. Negative Indexing**

Negative indexing starts from the end.

-1 → last

-2 → second last

-3 → third last

In [11]:
# Question 8: Display the last customer's record.

print(data[-1])

[ 1015 62000 13000  6000  4000    11]


In [12]:
# Question 9: Display the last customer's balance.
print(data[-1, 1])

62000


**9. Slicing**

Slicing is extremely important.

General syntax: `array[start:stop]`

Remember: stop is excluded.

In [13]:
# Question 10: Display the first five customers.
print(data[:5]) # This gives: Rows 0,1,2,3,4

[[ 1001 50000 12000  5000  3000     8]
 [ 1002 72000 15000  7000  4500    12]
 [ 1003 35000  8000  3000  2500     6]
 [ 1004 91000 20000  9000  6000    15]
 [ 1005 45000 10000  4000  3000     9]]


In [15]:
# Question 11: Display customers 6 to 10.
print(data[5:10])

[[  1006  68000  14000   6500   4000     11]
 [  1007  29000   7000   2500   2000      5]
 [  1008  83000  18000   8500   5000     14]
 [  1009  57000  11000   5500   3500     10]
 [  1010 102000  25000  12000   7000     18]]


In [16]:
# Question 12: Display the last five customers.
print(data[-5:])

[[ 1011 39000  9000  3500  2500     7]
 [ 1012 76000 16000  7500  4500    13]
 [ 1013 48000 10500  4500  3000     8]
 [ 1014 95000 22000 10000  6500    16]
 [ 1015 62000 13000  6000  4000    11]]


**10. Column Slicing**

In [17]:
# Question 13: Extract all customer IDs.
customer_ids = data[:, 0]  # colon(:) means All rows, column 0.
print(customer_ids)

[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015]


In [18]:
# Question 14: Extract all account balances.
balances = data[:, 1]
print(balances)

[ 50000  72000  35000  91000  45000  68000  29000  83000  57000 102000
  39000  76000  48000  95000  62000]


In [19]:
# Question 15: Extract all deposits.

deposits = data[:, 2]
print(deposits)

[12000 15000  8000 20000 10000 14000  7000 18000 11000 25000  9000 16000
 10500 22000 13000]


In [20]:
# Question 16: Extract all withdrawals.

withdrawals = data[:, 3]
print(withdrawals)

[ 5000  7000  3000  9000  4000  6500  2500  8500  5500 12000  3500  7500
  4500 10000  6000]


**11. Extract Multiple Columns**

In [21]:
# Question 17: Extract Balance, Deposit and Withdrawal columns.

financial_data = data[:, 1:4]
print(financial_data)

# Why 1:4?
# 1 → Balance
# 2 → Deposit
# 3 → Withdrawal

[[ 50000  12000   5000]
 [ 72000  15000   7000]
 [ 35000   8000   3000]
 [ 91000  20000   9000]
 [ 45000  10000   4000]
 [ 68000  14000   6500]
 [ 29000   7000   2500]
 [ 83000  18000   8500]
 [ 57000  11000   5500]
 [102000  25000  12000]
 [ 39000   9000   3500]
 [ 76000  16000   7500]
 [ 48000  10500   4500]
 [ 95000  22000  10000]
 [ 62000  13000   6000]]


**12. Arithmetic Operations**

Suppose the bank wants to calculate the new balance after deposit and withdrawal.

Formula: `New Balance = Balance + Deposit - Withdrawal`

In [23]:
# Question 18: Calculate new balance for every customer.

new_balance = data[:, 1] + data[:, 2] - data[:, 3]
print(new_balance)

# NumPy performs the calculation element by element.

[ 57000  80000  40000 102000  51000  75500  33500  92500  62500 115000
  44500  84500  54000 107000  69000]


**13. Calculate EMI-adjusted Balance**


In [24]:
# Question 19: Calculate balance after EMI deduction.
# Formula: Remaining Balance = Balance - EMI

remaining_balance = data[:, 1] - data[:, 4]
print(remaining_balance)

[47000 67500 32500 85000 42000 64000 27000 78000 53500 95000 36500 71500
 45000 88500 58000]


**14. Scalar Arithmetic**

Suppose the bank wants to give 5% interest on current balances.

In [26]:
# Question 20: Calculate 5% interest.

interest = data[:, 1] * 0.05
print(interest)

[2500. 3600. 1750. 4550. 2250. 3400. 1450. 4150. 2850. 5100. 1950. 3800.
 2400. 4750. 3100.]


In [27]:
# Question 21: Calculate balance after adding 5% interest.

balance_with_interest = data[:, 1] * 1.05
print(balance_with_interest)

[ 52500.  75600.  36750.  95550.  47250.  71400.  30450.  87150.  59850.
 107100.  40950.  79800.  50400.  99750.  65100.]


**15. Array-to-Array Operations**

Suppose the bank wants to compare deposits and withdrawals.

In [28]:
# Question 22: Calculate net transaction amount.
net_transaction = data[:, 2] - data[:, 3] # Deposit - Withdrawal
print(net_transaction)

[ 7000  8000  5000 11000  6000  7500  4500  9500  5500 13000  5500  8500
  6000 12000  7000]


**16. Aggregation Operations**

Now we can calculate overall banking statistics.

In [29]:
# Question 23: What is the total balance of all customers?
total_balance = np.sum(data[:, 1])
print(total_balance)

952000


In [30]:
# Question 24: What is the average account balance?
average_balance = np.mean(data[:, 1])
print(average_balance)

63466.666666666664


In [31]:
# Question 25: Find the highest account balance.
maximum_balance = np.max(data[:, 1])
print(maximum_balance)

102000


In [32]:
# Question 26: Find the lowest account balance.
minimum_balance = np.min(data[:, 1])
print(minimum_balance)

29000


**17. Finding Position of Maximum/Minimum**

In [33]:
# Question 27: Which customer's balance is highest?
index = np.argmax(data[:, 1])

print("Index:", index)
print("Customer ID:", data[index, 0])
print("Balance:", data[index, 1])

# np.argmax() returns the position of the maximum value.

Index: 9
Customer ID: 1010
Balance: 102000


In [34]:
# Similarly for min
index = np.argmin(data[:, 1])
print("Customer ID:", data[index, 0])

Customer ID: 1007


**18. Boolean Indexing**

In [35]:
# Question 28: Find customers whose balance is greater than ₹70,000.

high_balance = data[data[:, 1] > 70000]
print(high_balance)

[[  1002  72000  15000   7000   4500     12]
 [  1004  91000  20000   9000   6000     15]
 [  1008  83000  18000   8500   5000     14]
 [  1010 102000  25000  12000   7000     18]
 [  1012  76000  16000   7500   4500     13]
 [  1014  95000  22000  10000   6500     16]]
