<a href="https://colab.research.google.com/github/Nihcas001/data_analysis_using_Python/blob/main/06(B)_Traffic_Monitoring_Using_Numpy/traffic_monitoring_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
# Step 1 — Import NumPy
import numpy as np

In [23]:
# Step 2 — Create the Traffic Array
traffic = np.array([
    [101,  850, 42, 400,  80,  70, 300],
    [102, 1250, 28, 600, 120, 100, 430],
    [103,  650, 48, 300,  50,  40, 260],
    [104, 1450, 22, 700, 150, 120, 480],
    [105,  920, 35, 450,  90,  60, 320],
    [106, 1180, 30, 570, 110,  90, 410],
    [107,  540, 52, 250,  40,  30, 220],
    [108, 1600, 20, 800, 180, 140, 480],
    [109,  980, 38, 480,  85,  65, 350],
    [110, 1720, 18, 850, 200, 160, 510],
    [111,  720, 45, 350,  60,  45, 265],
    [112, 1320, 25, 650, 130, 110, 430],
    [113,  880, 40, 420,  75,  55, 330],
    [114, 1500, 21, 750, 160, 130, 460],
    [115, 1100, 32, 530, 100,  80, 390]
])

print(traffic)

[[ 101  850   42  400   80   70  300]
 [ 102 1250   28  600  120  100  430]
 [ 103  650   48  300   50   40  260]
 [ 104 1450   22  700  150  120  480]
 [ 105  920   35  450   90   60  320]
 [ 106 1180   30  570  110   90  410]
 [ 107  540   52  250   40   30  220]
 [ 108 1600   20  800  180  140  480]
 [ 109  980   38  480   85   65  350]
 [ 110 1720   18  850  200  160  510]
 [ 111  720   45  350   60   45  265]
 [ 112 1320   25  650  130  110  430]
 [ 113  880   40  420   75   55  330]
 [ 114 1500   21  750  160  130  460]
 [ 115 1100   32  530  100   80  390]]


**Step 3 — Understand Rows and Columns**

```
Column 0 → Region ID
Column 1 → Total Vehicles
Column 2 → Average Speed
Column 3 → Cars
Column 4 → Buses
Column 5 → Trucks
Column 6 → Two-Wheelers
```

In [24]:
# Get total vehicles from every region.
print(traffic[:, 1])
# Get average speed from every region.
print(traffic[:, 2])

[ 850 1250  650 1450  920 1180  540 1600  980 1720  720 1320  880 1500
 1100]
[42 28 48 22 35 30 52 20 38 18 45 25 40 21 32]


**Step 4 — Basic Array Properties**

In [25]:
# Question 1: Find number of dimensions.
print(traffic.ndim)

2


In [26]:
# 2: Find shape.
print(traffic.shape)

(15, 7)


In [27]:
# Question 3: Find total number of elements.
print(traffic.size)

105


**Step 5 — Indexing**

In [28]:
# Question 4: Display the first region's complete record.
print(traffic[0])

[101 850  42 400  80  70 300]


In [29]:
# Question 5: Display the first region's vehicle count.
print(traffic[0, 1])

850


In [32]:
# Question 6: Display the 10th region's average speed.
print(traffic[9, 2])

18


In [33]:
# Question 7: Display the last region.
print(traffic[-1])

[ 115 1100   32  530  100   80  390]


**Step 6 — Extract Important Columns**

In [34]:
# Question 8: Extract all vehicle counts.
vehicles = traffic[:, 1]
print(vehicles)

[ 850 1250  650 1450  920 1180  540 1600  980 1720  720 1320  880 1500
 1100]


In [35]:
# Question 9: Extract all average speeds.
speed = traffic[:, 2]
print(speed)

[42 28 48 22 35 30 52 20 38 18 45 25 40 21 32]


In [36]:
# Question 10: Extract region IDs.
region_ids = traffic[:, 0]
print(region_ids)

[101 102 103 104 105 106 107 108 109 110 111 112 113 114 115]


**Step 7 — NumPy Aggregation**

Aggregation means:

> Combining many values to obtain a summary.

Common NumPy aggregation functions are:

```
np.sum()
np.mean()
np.min()
np.max()
np.std()
np.median()
```

In [37]:
# Question 11: Find total vehicles across all regions.
total_vehicles = np.sum(vehicles)
print(total_vehicles)

16660


This answers:

> How many vehicles were recorded across all monitored regions?

In [38]:
# Question 12: Find average number of vehicles per region.
average_vehicles = np.mean(vehicles)
print(average_vehicles)

1110.6666666666667


In [39]:
# Question 13: Find the maximum number of vehicles recorded.
maximum_traffic = np.max(vehicles)
print(maximum_traffic)

1720


In [40]:
# Question 14: Find the minimum number of vehicles.
minimum_traffic = np.min(vehicles)
print(minimum_traffic)

540


In [41]:
# Question 15: Find standard deviation of vehicle counts.
traffic_std = np.std(vehicles)
print(traffic_std)

347.43760431031194


>A higher standard deviation means traffic volume varies more between regions.

**16. Aggregation Using axis**

This is an important concept.

Suppose we want the total number of:
```
vehicles
cars
buses
trucks
two-wheelers
```

In [42]:
# We select these columns:
vehicle_types = traffic[:, 1:]
print(np.sum(vehicle_types, axis=0))

[16660   496  8100  1630  1295  5635]


**What does axis=0 mean?**

It means:

>Calculate vertically, column by column.

So we get totals for each vehicle category.

In [43]:
# Question 16: Find average value of each traffic category.
category_average = np.mean(vehicle_types, axis=0)
print(category_average)

[1110.66666667   33.06666667  540.          108.66666667   86.33333333
  375.66666667]


**17. Boolean Operations**

Now we reach the main objective of this problem.

Suppose the traffic department defines:

>High-density traffic = more than 1,000 vehicles.


In [44]:
# We can create a Boolean condition:
high_traffic = vehicles > 1000
print(high_traffic)

[False  True False  True False  True False  True False  True False  True
 False  True  True]


The result looks like:

>[False  True False True ...]

This is a **Boolean mask.**

**18. What is Masking?**

For example:

```
vehicles > 1000
```

creates something like:

```
False
True
False
True
True
...
```

Then:

`vehicles[vehicles > 1000]`

returns only the values where the condition is **True**.

In [45]:
# Question 17: Find all regions having more than 1,000 vehicles.
high_density = traffic[traffic[:, 1] > 1000]

print(high_density)

[[ 102 1250   28  600  120  100  430]
 [ 104 1450   22  700  150  120  480]
 [ 106 1180   30  570  110   90  410]
 [ 108 1600   20  800  180  140  480]
 [ 110 1720   18  850  200  160  510]
 [ 112 1320   25  650  130  110  430]
 [ 114 1500   21  750  160  130  460]
 [ 115 1100   32  530  100   80  390]]


Read it as:

>Select rows from traffic where column 1 is greater than 1000.

**20. Display Only Region IDs**

In [46]:
# Question 18: Find IDs of high-density regions.
high_density_ids = traffic[traffic[:, 1] > 1000, 0]
print(high_density_ids)

[102 104 106 108 110 112 114 115]


This combines: masking & indexing

**21. Count High-Density Regions**

In [47]:
# Question 19: How many regions have more than 1,000 vehicles?
count = np.sum(traffic[:, 1] > 1000)
print(count)

8


**22. Boolean AND Operation**

Now suppose we define congestion as:

>Vehicles > 1,000 AND average speed < 30 km/h.

In [48]:
# Use & for AND ... not and
condition = (traffic[:, 1] > 1000) & (traffic[:, 2] < 30)
congested = traffic[condition]
print(congested)

[[ 102 1250   28  600  120  100  430]
 [ 104 1450   22  700  150  120  480]
 [ 108 1600   20  800  180  140  480]
 [ 110 1720   18  850  200  160  510]
 [ 112 1320   25  650  130  110  430]
 [ 114 1500   21  750  160  130  460]]


In [49]:
# 23. Find IDs of Congested Regions
congested_ids = traffic[condition, 0]
print(congested_ids)

[102 104 108 110 112 114]


**24. Boolean OR Operation**

Suppose the traffic department wants to identify regions where:

> Vehicles > 1,500 OR speed < 20 km/h.

In [50]:
# Use | for OR .. Not or
condition = (traffic[:, 1] > 1500) | (traffic[:, 2] < 20)
result = traffic[condition]
print(result)

[[ 108 1600   20  800  180  140  480]
 [ 110 1720   18  850  200  160  510]]


**25. Boolean NOT Operation**

Suppose we want regions where traffic is not greater than 1,000.

In [51]:
# Use ~ for NOT ... Don't use NOT
condition = ~(traffic[:, 1] > 1000)
result = traffic[condition]
print(result)

[[101 850  42 400  80  70 300]
 [103 650  48 300  50  40 260]
 [105 920  35 450  90  60 320]
 [107 540  52 250  40  30 220]
 [109 980  38 480  85  65 350]
 [111 720  45 350  60  45 265]
 [113 880  40 420  75  55 330]]


**26. Multiple Conditions**

A region is severely congested if:

```
Vehicles > 1,200
Average speed < 30 km/h
AND trucks > 100
```

In [52]:
severe = (
    (traffic[:, 1] > 1200) &
    (traffic[:, 2] < 30) &
    (traffic[:, 5] > 100)
)

result = traffic[severe]
print(result)

# This is a good example of multiple Boolean conditions.

[[ 104 1450   22  700  150  120  480]
 [ 108 1600   20  800  180  140  480]
 [ 110 1720   18  850  200  160  510]
 [ 112 1320   25  650  130  110  430]
 [ 114 1500   21  750  160  130  460]]


**27. Fancy Indexing**

Now we move to another important NumPy concept.

Suppose we specifically want regions:

```
102, 105, 110, 114
```
Their row positions are:

```
1, 4, 9, 13
```

In [53]:
indices = [1, 4, 9, 13]
selected_regions = traffic[indices]
print(selected_regions)

[[ 102 1250   28  600  120  100  430]
 [ 105  920   35  450   90   60  320]
 [ 110 1720   18  850  200  160  510]
 [ 114 1500   21  750  160  130  460]]


This is called **fancy indexing.**

**28. Fancy Indexing with Columns**

Suppose we only want:


```
Region ID
Vehicles
Average Speed
```

These are columns:

`0, 1, 2`

In [54]:
selected_columns = traffic[:, [0, 1, 2]]

print(selected_columns)

# This is also fancy indexing.

[[ 101  850   42]
 [ 102 1250   28]
 [ 103  650   48]
 [ 104 1450   22]
 [ 105  920   35]
 [ 106 1180   30]
 [ 107  540   52]
 [ 108 1600   20]
 [ 109  980   38]
 [ 110 1720   18]
 [ 111  720   45]
 [ 112 1320   25]
 [ 113  880   40]
 [ 114 1500   21]
 [ 115 1100   32]]


**29. Fancy Indexing — Specific Regions and Columns**

In [55]:
# We can combine both.
indices = [1, 4, 9, 13]
result = traffic[indices][:, [0, 1, 2]]
print(result)

[[ 102 1250   28]
 [ 105  920   35]
 [ 110 1720   18]
 [ 114 1500   21]]


This gives: Selected regions + selected columns.

**30. Find the Most Congested Region**

We can use argmax().

In [57]:
# Question 20: Find the index of the region with maximum traffic.
index = np.argmax(traffic[:, 1]) # argmax() gives the position, not the actual maximum value.
print(index)

9


In [58]:
# Now find its details:
print("Region ID:", traffic[index, 0])
print("Vehicles:", traffic[index, 1])
print("Speed:", traffic[index, 2])

Region ID: 110
Vehicles: 1720
Speed: 18


In [59]:
# 31. Find Least Busy Region
index = np.argmin(traffic[:, 1])
print("Region ID:", traffic[index, 0])
print("Vehicles:", traffic[index, 1])

Region ID: 107
Vehicles: 540


In [60]:
# 32. Ranking Regions Using argsort()
# Suppose we want to rank regions according to traffic volume.
ranking = np.argsort(traffic[:, 1])
print(ranking)

# This returns row indices sorted according to vehicle count.

[ 6  2 10  0 12  4  8 14  5  1 11  3 13  7  9]


In [61]:
# For descending order:
ranking = np.argsort(traffic[:, 1])[::-1]
print(ranking)

[ 9  7 13  3 11  1  5 14  8  4 12  0 10  2  6]


In [62]:
# Now display the top 5 regions:
top5 = traffic[ranking[:5]]
print(top5)

[[ 110 1720   18  850  200  160  510]
 [ 108 1600   20  800  180  140  480]
 [ 114 1500   21  750  160  130  460]
 [ 104 1450   22  700  150  120  480]
 [ 112 1320   25  650  130  110  430]]


This is a very useful application of **fancy indexing.**

In [63]:
# 33. Top 5 High-Traffic Regions

vehicles = traffic[:, 1]
ranking = np.argsort(vehicles)[::-1]
top5 = traffic[ranking[:5]]
print(top5)

[[ 110 1720   18  850  200  160  510]
 [ 108 1600   20  800  180  140  480]
 [ 114 1500   21  750  160  130  460]
 [ 104 1450   22  700  150  120  480]
 [ 112 1320   25  650  130  110  430]]


Read this as:

```
Sort vehicle positions.
Reverse them for descending order.
Take first 5 positions.
Use those positions to select rows.
```

34. Using np.where()

Suppose the traffic department wants to classify regions as:

```
High Density → Vehicles > 1200
Normal       → Otherwise
```

In [64]:
traffic_level = np.where(
    traffic[:, 1] > 1200,
    "High Density",
    "Normal"
)

print(traffic_level)

['Normal' 'High Density' 'Normal' 'High Density' 'Normal' 'Normal'
 'Normal' 'High Density' 'Normal' 'High Density' 'Normal' 'High Density'
 'Normal' 'High Density' 'Normal']


**35. Three-Level Traffic Classification**

We can make it more realistic:

```
< 800       → Low
800–1200    → Medium
> 1200      → High
```

In [65]:
traffic_level = np.where(
    traffic[:, 1] > 1200,
    "High",
    np.where(
        traffic[:, 1] >= 800,
        "Medium",
        "Low"
    )
)

print(traffic_level)

['Medium' 'High' 'Low' 'High' 'Medium' 'Medium' 'Low' 'High' 'Medium'
 'High' 'Low' 'High' 'Medium' 'High' 'Medium']


**36. Calculate Percentage of High-Density Regions**

Suppose we want to know:

>What percentage of monitored regions have more than 1,000 vehicles?

In [66]:
high_density_count = np.sum(traffic[:, 1] > 1000)
percentage = (high_density_count / traffic.shape[0]) * 100
print("High-density percentage:", percentage)

High-density percentage: 53.333333333333336


In [68]:
traffic.shape[0] # means: Number of rows.

15

**37. Average Speed in High-Density Regions**


In [69]:
mask = traffic[:, 1] > 1000
average_speed = np.mean(traffic[mask, 2])
print("Average speed:", average_speed)

Average speed: 24.5


We first select high-density regions and then calculate their average speed.

**38. Average Traffic of Congested Regions**

Let's use our congestion definition:

```
Vehicles > 1000
AND
Speed < 30
```

In [70]:
mask = (traffic[:, 1] > 1000) & (traffic[:, 2] < 30)
average_traffic = np.mean(traffic[mask, 1])
print("Average traffic:", average_traffic)

Average traffic: 1473.3333333333333


**39. Find Regions with Heavy Truck Traffic**

Suppose:

>Heavy truck traffic = trucks > 100.

In [71]:
mask = traffic[:, 5] > 100
result = traffic[mask]
print(result)

[[ 104 1450   22  700  150  120  480]
 [ 108 1600   20  800  180  140  480]
 [ 110 1720   18  850  200  160  510]
 [ 112 1320   25  650  130  110  430]
 [ 114 1500   21  750  160  130  460]]


**40. Find Regions Dominated by Two-Wheelers**

Suppose we want regions where:

>Two-wheelers > 400

In [72]:
mask = traffic[:, 6] > 400
result = traffic[mask]
print(result)

[[ 102 1250   28  600  120  100  430]
 [ 104 1450   22  700  150  120  480]
 [ 106 1180   30  570  110   90  410]
 [ 108 1600   20  800  180  140  480]
 [ 110 1720   18  850  200  160  510]
 [ 112 1320   25  650  130  110  430]
 [ 114 1500   21  750  160  130  460]]


In [73]:
# 41. Compare Cars and Two-Wheelers
# Find regions where two-wheelers are greater than cars.

mask = traffic[:, 6] > traffic[:, 3]
result = traffic[mask]
print(result)

[]


This demonstrates an important feature of NumPy:

>Comparing two arrays element by element.

**42. Calculate Vehicle Composition**

Suppose we want to calculate the percentage of cars among all vehicles.

In [74]:
cars = traffic[:, 3]
vehicles = traffic[:, 1]
car_percentage = (cars / vehicles) * 100
print(car_percentage)

[47.05882353 48.         46.15384615 48.27586207 48.91304348 48.30508475
 46.2962963  50.         48.97959184 49.41860465 48.61111111 49.24242424
 47.72727273 50.         48.18181818]


In [75]:
# We can do the same for buses:
bus_percentage = (traffic[:, 4] / traffic[:, 1]) * 100
print(bus_percentage)

[ 9.41176471  9.6         7.69230769 10.34482759  9.7826087   9.3220339
  7.40740741 11.25        8.67346939 11.62790698  8.33333333  9.84848485
  8.52272727 10.66666667  9.09090909]


In [76]:
# And two-wheelers:
two_wheeler_percentage = (traffic[:, 6] / traffic[:, 1]) * 100
print(two_wheeler_percentage)

[35.29411765 34.4        40.         33.10344828 34.7826087  34.74576271
 40.74074074 30.         35.71428571 29.65116279 36.80555556 32.57575758
 37.5        30.66666667 35.45454545]


**43. A Useful Real-World Traffic Metric**

We can create a simple congestion score.

For example:

`Congestion Score = Vehicles / Average Speed`

In [77]:
congestion_score = traffic[:, 1] / traffic[:, 2]
print(congestion_score)

[20.23809524 44.64285714 13.54166667 65.90909091 26.28571429 39.33333333
 10.38461538 80.         25.78947368 95.55555556 16.         52.8
 22.         71.42857143 34.375     ]


Higher score means:

>Many vehicles + low speed → greater congestion.

Now find the region with the highest score:

In [78]:
index = np.argmax(congestion_score)

print("Most congested region:", traffic[index, 0])
print("Congestion score:", congestion_score[index])

Most congested region: 110
Congestion score: 95.55555555555556


This is a nice extension because students see how NumPy can be used to create a **new analytical metric.**

**44. Important Difference: Masking vs Fancy Indexing**

Students often confuse these two.

Masking

You select data using a condition:

`traffic[traffic[:, 1] > 1000]`

Meaning:

>Select regions where vehicles > 1000.

Fancy indexing

You select data using specific indices:

`traffic[[1, 4, 9, 13]]`

Meaning:

>Select rows 1, 4, 9 and 13.

Easy way to remember

```
Masking       → "Which data satisfies my condition?"
Fancy indexing → "Give me these specific positions."
```